version: '3.9'

services:
  postgresql:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: arun
      POSTGRES_PASSWORD: arun
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    container_name: mongo_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: arun
      MONGO_INITDB_ROOT_PASSWORD: arun
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - microservices-net
    restart: unless-stopped

  mongo-express:
    container_name: mongo_express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: arun
      ME_CONFIG_MONGODB_ADMINPASSWORD: arun
      ME_CONFIG_MONGODB_SERVER: mongo_db  # Match the container name for MongoDB
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    restart: unless-stopped
    depends_on:
      - mongodb

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
